// Internal lead notes — Phase 1 (text only). Backed by public.lead_notes,
// applied to PROD 2026-08-26. NEVER customer-visible: nothing under
// supabase/functions, api/ or the PDF/email pipelines may import this module.
//
// lead_notes and get_staff_names are not yet in the generated Database types
// (types.ts is regenerated by a --project-ref scoped command Michael runs by
// hand), so this module talks to an untyped view of the client — the same
// approach as FanOutRpcClient in notifications.ts. The table's column
// privileges allow INSERT of (lead_id, author_id, body) and UPDATE of
// (deleted_at) only; RLS delegates visibility to the lead itself.

import type { SupabaseClient } from '@supabase/supabase-js';

import { supabase } from '@/integrations/supabase/client';
import { logNoteAdded } from '@/lib/api/fieldEditLog';
import { captureBusinessError } from '@/lib/sentry';

export interface LeadNoteRow {
  id: string;
  lead_id: string;
  author_id: string;
  body: string;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}

export interface LeadNote extends LeadNoteRow {
  /** Resolved from profiles via get_staff_names; null when unresolved. */
  authorName: string | null;
}

export type LeadNoteErrorCode =
  | 'EMPTY_BODY'
  | 'BODY_TOO_LONG'
  | 'NOT_AUTHENTICATED'
  | 'INSERT_FAILED'
  | 'LIST_FAILED'
  | 'DELETE_FAILED';

export class LeadNoteError extends Error {
  readonly code: LeadNoteErrorCode;

  constructor(code: LeadNoteErrorCode, message: string) {
    super(message);
    this.name = 'LeadNoteError';
    this.code = code;
  }
}

/** Mirrors CHECK lead_notes_body_max_len. */
export const LEAD_NOTE_MAX_LENGTH = 10000;

const LEAD_NOTES_TABLE = 'lead_notes';
const STAFF_NAMES_RPC = 'get_staff_names';
const LEAD_NOTE_COLUMNS = 'id, lead_id, author_id, body, created_at, updated_at, deleted_at';

interface StaffNameRow {
  id: string;
  full_name: string | null;
}

const db = supabase as unknown as SupabaseClient;

/**
 * Live (non-deleted) notes for one lead, newest first, with author names
 * resolved through get_staff_names. Name resolution failing degrades to
 * authorName = null rather than hiding the feed.
 */
export async function listLeadNotes(leadId: string): Promise<LeadNote[]> {
  const { data, error } = await db
    .from(LEAD_NOTES_TABLE)
    .select(LEAD_NOTE_COLUMNS)
    .eq('lead_id', leadId)
    .is('deleted_at', null)
    .order('created_at', { ascending: false });

  if (error) {
    captureBusinessError('Failed to list lead notes', { leadId, error: error.message });
    throw new LeadNoteError('LIST_FAILED', `Failed to load notes: ${error.message}`);
  }

  const rows = (data ?? []) as LeadNoteRow[];
  const names = await fetchStaffNames(rows.map((row) => row.author_id));

  return rows.map((row) => ({ ...row, authorName: names.get(row.author_id) ?? null }));
}

export interface CreateLeadNoteInput {
  leadId: string;
  body: string;
  /** Display name for the activities projection (logNoteAdded), not stored on the note. */
  authorName: string;
}

/**
 * Insert a note as the signed-in user, then project it into the activity
 * timeline via the existing logNoteAdded (activity_type 'note_added').
 * Throws LeadNoteError so the UI can surface and roll back.
 */
export async function createLeadNote(input: CreateLeadNoteInput): Promise<LeadNoteRow> {
  const body = input.body.trim();
  if (!body) {
    throw new LeadNoteError('EMPTY_BODY', 'A note needs some text.');
  }
  if (body.length > LEAD_NOTE_MAX_LENGTH) {
    throw new LeadNoteError('BODY_TOO_LONG', `Notes are limited to ${LEAD_NOTE_MAX_LENGTH} characters.`);
  }

  const { data: userData } = await db.auth.getUser();
  const authorId = userData?.user?.id;
  if (!authorId) {
    throw new LeadNoteError('NOT_AUTHENTICATED', 'You need to be signed in to add a note.');
  }

  const { data, error } = await db
    .from(LEAD_NOTES_TABLE)
    .insert({ lead_id: input.leadId, author_id: authorId, body })
    .select(LEAD_NOTE_COLUMNS)
    .single();

  if (error || !data) {
    captureBusinessError('Failed to create lead note', {
      leadId: input.leadId,
      error: error?.message ?? 'no row returned',
    });
    throw new LeadNoteError('INSERT_FAILED', `Failed to save note: ${error?.message ?? 'no row returned'}`);
  }

  await logNoteAdded({ leadId: input.leadId, noteText: body, authorName: input.authorName });

  return data as LeadNoteRow;
}

/**
 * Soft delete (stamps deleted_at). RLS + column privileges mean only the
 * author can do this; a non-author or an already-deleted note matches zero
 * rows, which is reported as DELETE_FAILED instead of silently succeeding.
 */
export async function softDeleteLeadNote(noteId: string): Promise<void> {
  const { data, error } = await db
    .from(LEAD_NOTES_TABLE)
    .update({ deleted_at: new Date().toISOString() })
    .eq('id', noteId)
    .is('deleted_at', null)
    .select('id');

  if (error) {
    captureBusinessError('Failed to delete lead note', { noteId, error: error.message });
    throw new LeadNoteError('DELETE_FAILED', `Failed to delete note: ${error.message}`);
  }
  if (!data || data.length === 0) {
    throw new LeadNoteError('DELETE_FAILED', 'This note could not be deleted — only its author can remove it.');
  }
}

async function fetchStaffNames(authorIds: string[]): Promise<Map<string, string>> {
  const uniqueIds = Array.from(new Set(authorIds));
  const names = new Map<string, string>();
  if (uniqueIds.length === 0) return names;

  const { data, error } = await db.rpc(STAFF_NAMES_RPC, { p_user_ids: uniqueIds });

  if (error) {
    captureBusinessError('Failed to resolve lead note author names', { error: error.message });
    return names;
  }

  for (const row of (data ?? []) as StaffNameRow[]) {
    if (row.full_name) names.set(row.id, row.full_name);
  }
  return names;
}
