// Internal lead notes — Phase 1 (text only). Backed by public.lead_notes,
// applied to PROD 2026-08-26. NEVER customer-visible: nothing under
// supabase/functions, api/ or the PDF/email pipelines may import this module.
//
// lead_notes and get_staff_names are not yet in the generated Database types
// (types.ts is regenerated by a --project-ref scoped command Michael runs by
// hand), so this module talks to an untyped view of the client — the same
// approach as FanOutRpcClient in notifications.ts. The table's column
// privileges allow INSERT of (lead_id, author_id, body) and UPDATE of
// (deleted_at) only; RLS delegates visibility to the lead itself.

import type { SupabaseClient } from '@supabase/supabase-js';

import { supabase } from '@/integrations/supabase/client';
import { logNoteAdded } from '@/lib/api/fieldEditLog';
import { captureBusinessError } from '@/lib/sentry';

export interface LeadNoteRow {
  id: string;
  lead_id: string;
  author_id: string;
  body: string;
  created_at: string;
  updated_at: string;
  deleted_at: string | null;
}

export interface LeadNote extends LeadNoteRow {
  /** Resolved from profiles via get_staff_names; null when unresolved. */
  authorName: string | null;
}

/** One @mention on a note. fullName resolves through get_staff_names. */
export interface NoteMention {
  noteId: string;
  userId: string;
  fullName: string | null;
}

/** A staff member who can be @mentioned. */
export interface MentionCandidate {
  id: string;
  fullName: string;
}

export type LeadNoteErrorCode =
  | 'EMPTY_BODY'
  | 'BODY_TOO_LONG'
  | 'NOT_AUTHENTICATED'
  | 'INSERT_FAILED'
  | 'LIST_FAILED'
  | 'DELETE_FAILED'
  | 'MENTION_FAILED'
  | 'STAFF_LIST_FAILED';

export class LeadNoteError extends Error {
  readonly code: LeadNoteErrorCode;

  constructor(code: LeadNoteErrorCode, message: string) {
    super(message);
    this.name = 'LeadNoteError';
    this.code = code;
  }
}

/** Mirrors CHECK lead_notes_body_max_len. */
export const LEAD_NOTE_MAX_LENGTH = 10000;

const LEAD_NOTES_TABLE = 'lead_notes';
const LEAD_NOTE_MENTIONS_TABLE = 'lead_note_mentions';
const USER_ROLES_TABLE = 'user_roles';
const STAFF_NAMES_RPC = 'get_staff_names';
const ADD_MENTIONS_RPC = 'add_lead_note_mentions';
const LEAD_NOTE_COLUMNS = 'id, lead_id, author_id, body, created_at, updated_at, deleted_at';

interface StaffNameRow {
  id: string;
  full_name: string | null;
}

const db = supabase as unknown as SupabaseClient;

/**
 * Live (non-deleted) notes for one lead, newest first, with author names
 * resolved through get_staff_names. Name resolution failing degrades to
 * authorName = null rather than hiding the feed.
 */
export async function listLeadNotes(leadId: string): Promise<LeadNote[]> {
  const { data, error } = await db
    .from(LEAD_NOTES_TABLE)
    .select(LEAD_NOTE_COLUMNS)
    .eq('lead_id', leadId)
    .is('deleted_at', null)
    .order('created_at', { ascending: false });

  if (error) {
    captureBusinessError('Failed to list lead notes', { leadId, error: error.message });
    throw new LeadNoteError('LIST_FAILED', `Failed to load notes: ${error.message}`);
  }

  const rows = (data ?? []) as LeadNoteRow[];
  const names = await fetchStaffNames(rows.map((row) => row.author_id));

  return rows.map((row) => ({ ...row, authorName: names.get(row.author_id) ?? null }));
}

export interface CreateLeadNoteInput {
  leadId: string;
  body: string;
  /** Display name for the activities projection (logNoteAdded), not stored on the note. */
  authorName: string;
}

/**
 * Insert a note as the signed-in user, then project it into the activity
 * timeline via the existing logNoteAdded (activity_type 'note_added').
 * Throws LeadNoteError so the UI can surface and roll back.
 */
export async function createLeadNote(input: CreateLeadNoteInput): Promise<LeadNoteRow> {
  const body = input.body.trim();
  if (!body) {
    throw new LeadNoteError('EMPTY_BODY', 'A note needs some text.');
  }
  if (body.length > LEAD_NOTE_MAX_LENGTH) {
    throw new LeadNoteError('BODY_TOO_LONG', `Notes are limited to ${LEAD_NOTE_MAX_LENGTH} characters.`);
  }

  const { data: userData } = await db.auth.getUser();
  const authorId = userData?.user?.id;
  if (!authorId) {
    throw new LeadNoteError('NOT_AUTHENTICATED', 'You need to be signed in to add a note.');
  }

  const { data, error } = await db
    .from(LEAD_NOTES_TABLE)
    .insert({ lead_id: input.leadId, author_id: authorId, body })
    .select(LEAD_NOTE_COLUMNS)
    .single();

  if (error || !data) {
    captureBusinessError('Failed to create lead note', {
      leadId: input.leadId,
      error: error?.message ?? 'no row returned',
    });
    throw new LeadNoteError('INSERT_FAILED', `Failed to save note: ${error?.message ?? 'no row returned'}`);
  }

  await logNoteAdded({ leadId: input.leadId, noteText: body, authorName: input.authorName });

  return data as LeadNoteRow;
}

/**
 * Soft delete (stamps deleted_at). RLS + column privileges mean only the
 * author can do this; a non-author or an already-deleted note matches zero
 * rows, which is reported as DELETE_FAILED instead of silently succeeding.
 */
export async function softDeleteLeadNote(noteId: string): Promise<void> {
  const { data, error } = await db
    .from(LEAD_NOTES_TABLE)
    .update({ deleted_at: new Date().toISOString() })
    .eq('id', noteId)
    .is('deleted_at', null)
    .select('id');

  if (error) {
    captureBusinessError('Failed to delete lead note', { noteId, error: error.message });
    throw new LeadNoteError('DELETE_FAILED', `Failed to delete note: ${error.message}`);
  }
  if (!data || data.length === 0) {
    throw new LeadNoteError('DELETE_FAILED', 'This note could not be deleted — only its author can remove it.');
  }
}

async function fetchStaffNames(authorIds: string[]): Promise<Map<string, string>> {
  const uniqueIds = Array.from(new Set(authorIds));
  const names = new Map<string, string>();
  if (uniqueIds.length === 0) return names;

  const { data, error } = await db.rpc(STAFF_NAMES_RPC, { p_user_ids: uniqueIds });

  if (error) {
    captureBusinessError('Failed to resolve lead note author names', { error: error.message });
    return names;
  }

  for (const row of (data ?? []) as StaffNameRow[]) {
    if (row.full_name) names.set(row.id, row.full_name);
  }
  return names;
}

// ---------------------------------------------------------------------------
// @mentions
//
// public.profiles is own-row-only, so names for anyone but yourself can only
// come from get_staff_names (SECURITY DEFINER). user_roles, by contrast, is
// readable by any authenticated user, so the candidate id list is a plain
// select and only the names need the RPC.
// ---------------------------------------------------------------------------

interface MentionRange {
  start: number;
  end: number;
  name: string;
}

/**
 * Locate "@Full Name" spans in a note body.
 *
 * Candidates are matched longest-first and claimed spans are never reused, so
 * a staff member called "Clay" can never match inside "@Clayton Jenkins".
 * Matching is case-insensitive; offsets index the ORIGINAL body.
 */
function findMentionRanges(body: string, names: string[]): MentionRange[] {
  const lower = body.toLowerCase();
  const ranges: MentionRange[] = [];
  const ordered = [...names]
    .filter((name) => name.trim().length > 0)
    .sort((a, b) => b.trim().length - a.trim().length);

  for (const name of ordered) {
    const token = `@${name.trim().toLowerCase()}`;
    let from = 0;
    for (;;) {
      const start = lower.indexOf(token, from);
      if (start === -1) break;
      const end = start + token.length;
      const overlaps = ranges.some((range) => start < range.end && end > range.start);
      if (!overlaps) ranges.push({ start, end, name });
      from = end;
    }
  }

  return ranges.sort((a, b) => a.start - b.start);
}

/**
 * Resolve the "@Full Name" tokens in a body to staff user ids. Two staff
 * sharing a full name both resolve, so an ambiguous mention over-notifies
 * rather than silently notifying the wrong person.
 */
export function parseMentions(body: string, staff: MentionCandidate[]): string[] {
  const idsByName = new Map<string, string[]>();
  for (const candidate of staff) {
    const key = candidate.fullName.trim().toLowerCase();
    idsByName.set(key, [...(idsByName.get(key) ?? []), candidate.id]);
  }

  const ids = new Set<string>();
  for (const range of findMentionRanges(body, staff.map((candidate) => candidate.fullName))) {
    for (const id of idsByName.get(range.name.trim().toLowerCase()) ?? []) ids.add(id);
  }
  return Array.from(ids);
}

export interface NoteBodySegment {
  text: string;
  isMention: boolean;
}

/**
 * Split a body into plain and mention segments for rendering. Returns the
 * original text as a single plain segment when nothing matches, so the caller
 * can always render segments rather than branching.
 */
export function segmentNoteBody(body: string, mentionNames: string[]): NoteBodySegment[] {
  const ranges = findMentionRanges(body, mentionNames);
  if (ranges.length === 0) return [{ text: body, isMention: false }];

  const segments: NoteBodySegment[] = [];
  let cursor = 0;
  for (const range of ranges) {
    if (range.start > cursor) {
      segments.push({ text: body.slice(cursor, range.start), isMention: false });
    }
    segments.push({ text: body.slice(range.start, range.end), isMention: true });
    cursor = range.end;
  }
  if (cursor < body.length) segments.push({ text: body.slice(cursor), isMention: false });
  return segments;
}

/** Every staff member who can be @mentioned, by display name. */
export async function listStaffForMentions(): Promise<MentionCandidate[]> {
  const { data, error } = await db.from(USER_ROLES_TABLE).select('user_id');

  if (error) {
    captureBusinessError('Failed to list mention candidates', { error: error.message });
    throw new LeadNoteError('STAFF_LIST_FAILED', `Failed to load the team list: ${error.message}`);
  }

  const ids = Array.from(
    new Set(
      ((data ?? []) as Array<{ user_id: string | null }>)
        .map((row) => row.user_id)
        .filter((id): id is string => Boolean(id)),
    ),
  );
  if (ids.length === 0) return [];

  const names = await fetchStaffNames(ids);
  return ids
    .filter((id) => names.has(id))
    .map((id) => ({ id, fullName: names.get(id) as string }))
    .sort((a, b) => a.fullName.localeCompare(b.fullName));
}

/**
 * Mentions for every live note on a lead, grouped by note id. Keyed on
 * lead_id (not note ids) so it runs in parallel with listLeadNotes instead of
 * waterfalling behind it. Failure degrades to an empty map — mentions are
 * decoration, and the feed must still render without them.
 */
export async function listNoteMentions(leadId: string): Promise<Map<string, NoteMention[]>> {
  const byNote = new Map<string, NoteMention[]>();

  const { data, error } = await db
    .from(LEAD_NOTE_MENTIONS_TABLE)
    .select('note_id, mentioned_user_id')
    .eq('lead_id', leadId);

  if (error) {
    captureBusinessError('Failed to list lead note mentions', { leadId, error: error.message });
    return byNote;
  }

  const rows = (data ?? []) as Array<{ note_id: string; mentioned_user_id: string }>;
  if (rows.length === 0) return byNote;

  const names = await fetchStaffNames(rows.map((row) => row.mentioned_user_id));
  for (const row of rows) {
    const mention: NoteMention = {
      noteId: row.note_id,
      userId: row.mentioned_user_id,
      fullName: names.get(row.mentioned_user_id) ?? null,
    };
    byNote.set(row.note_id, [...(byNote.get(row.note_id) ?? []), mention]);
  }
  return byNote;
}

/**
 * Persist the mention linkage and notify each mentioned person, via the
 * author-only SECURITY DEFINER RPC. Returns the number of people notified.
 * The RPC is idempotent: calling it twice never re-notifies.
 */
export async function addLeadNoteMentions(noteId: string, userIds: string[]): Promise<number> {
  if (userIds.length === 0) return 0;

  const { data, error } = await db.rpc(ADD_MENTIONS_RPC, {
    p_note_id: noteId,
    p_user_ids: userIds,
  });

  if (error) {
    captureBusinessError('Failed to persist lead note mentions', { noteId, error: error.message });
    throw new LeadNoteError('MENTION_FAILED', `Note saved, but the mentions could not be recorded: ${error.message}`);
  }

  return typeof data === 'number' ? data : 0;
}
