/**
 * Public API for creating leads from the request inspection form
 * This file handles form submissions from non-authenticated users
 */

import { supabase } from '@/integrations/supabase/client';
import type { Database } from '@/integrations/supabase/types';

type LeadInsert = Database['public']['Tables']['leads']['Insert'];

export type BookingUrgency =
  | 'ASAP'
  | 'within_week'
  | 'couple_weeks'
  | 'within_month'
  | 'couple_months';

export interface CreatePublicLeadInput {
  full_name: string;
  email: string;
  phone: string;
  property_address_street: string;
  property_address_suburb: string;
  property_address_postcode: string;
  issue_description: string;
  urgency: BookingUrgency;
}

export interface CreatePublicLeadResult {
  lead_id: string;
  lead_number: string | null;
  full_name: string;
  email: string;
  property_address: string;
  urgency: string;
}

/**
 * Create a new lead from public inspection request form
 * @param input - Form data from the public request inspection page
 * @returns Created lead with essential information
 */
export async function createPublicLead(
  input: CreatePublicLeadInput
): Promise<CreatePublicLeadResult> {
  try {
    // Prepare lead data
    const leadData: LeadInsert = {
      full_name: input.full_name,
      email: input.email,
      phone: input.phone,
      property_address_street: input.property_address_street,
      property_address_suburb: input.property_address_suburb,
      property_address_postcode: input.property_address_postcode,
      property_address_state: 'VIC',
      issue_description: input.issue_description,
      urgency: input.urgency,
      lead_source: 'website',
      status: 'new_lead',
    };

    // Insert lead into database
    // Note: We don't use .select() because anonymous users don't have SELECT permission
    // The lead will be created successfully, we just can't read it back
    const { error } = await supabase
      .from('leads')
      .insert(leadData);

    if (error) {
      console.error('❌ Error creating lead:', error);
      throw new Error(`Failed to create lead: ${error.message}`);
    }

    // Generate a temporary reference number for the success page
    // The actual lead_number will be generated by the database trigger
    const tempRefNumber = `WEB-${Date.now().toString().slice(-6)}`;


    // Return formatted result
    // Note: We return the input data since we can't read back from database
    return {
      lead_id: tempRefNumber, // Temporary reference
      lead_number: tempRefNumber,
      full_name: input.full_name,
      email: input.email,
      property_address: `${input.property_address_street}, ${input.property_address_suburb}`,
      urgency: input.urgency,
    };
  } catch (error) {
    console.error('❌ Failed to create public lead:', error);

    // Provide user-friendly error message
    if (error instanceof Error) {
      throw new Error(error.message);
    }

    throw new Error('An unexpected error occurred while submitting your request. Please try again or call us at 1800 954 117.');
  }
}

/**
 * Urgency options for the booking form dropdown
 */
export const URGENCY_OPTIONS: Array<{
  value: BookingUrgency;
  label: string;
  description: string;
}> = [
    {
      value: 'ASAP',
      label: 'ASAP - As soon as possible',
      description: 'Urgent - need help immediately'
    },
    {
      value: 'within_week',
      label: 'Within a week',
      description: 'Need service in the next 7 days'
    },
    {
      value: 'couple_weeks',
      label: 'Next couple of weeks',
      description: 'Flexible - within 2 weeks'
    },
    {
      value: 'within_month',
      label: 'Within a month',
      description: 'Not urgent - within 30 days'
    },
    {
      value: 'couple_months',
      label: 'Next couple of months',
      description: 'Planning ahead - 2-3 months'
    },
  ];
