-- =============================================================================
-- Seed: 50 realistic Melbourne leads for pipeline/dashboard testing
-- Target technician: michaelyoussef396@gmail.com
-- Date range: 2026-01-20 to 2026-02-19 (30-day spread)
--
-- HOW TO RUN:
-- 1. Go to https://supabase.com/dashboard/project/ecyivrxjpsmjmexqatym/sql
-- 2. Paste this entire file
-- 3. Click "Run"
--
-- NOTES:
-- - lead_number is auto-generated by trigger (MRC-2026-XXXX)
-- - id uses default gen_random_uuid()
-- - property_address_state defaults to 'VIC'
-- - Timestamps use AT TIME ZONE for correct Melbourne AEDT (UTC+11)
-- =============================================================================

DO $$
DECLARE
  tech_id uuid := 'd22fa3bb-9bf0-4e27-8681-1f09841f0d8e';
BEGIN

  -- =========================================================================
  -- GROUP 1: new_lead (15 leads) — Fresh, unassigned
  -- Created: Feb 13-19 2026
  -- =========================================================================
  INSERT INTO public.leads (
    full_name, email, phone,
    property_address_street, property_address_suburb, property_address_state, property_address_postcode,
    property_zone, lead_source, issue_description, urgency, property_type,
    status, created_at
  ) VALUES
  (
    'Sarah Chen', 'sarah.chen@gmail.com', '0412300001',
    '45 Church Street', 'Richmond', 'VIC', '3121',
    1, 'Website Form',
    'Noticed black mould growing in the corner of our bathroom ceiling near the exhaust fan. It seems to be spreading and the grout between tiles is discoloured. Very concerned about health impacts for our young children.',
    'high', 'residential_house',
    'new_lead', '2026-02-19 09:15:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'James O''Brien', 'james.obrien@outlook.com', '0412300002',
    '12 Glenferrie Road', 'Hawthorn', 'VIC', '3122',
    2, 'Google Search (Organic)',
    'Found extensive mould behind the wardrobe in our master bedroom after noticing a musty smell. The wall is damp to touch and the paint is bubbling. House is around 60 years old with no subfloor ventilation.',
    'high', 'residential_house',
    'new_lead', '2026-02-19 10:30:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'Priya Sharma', 'priya.sharma@email.com', '0412300003',
    'Unit 8/120 Toorak Road', 'South Yarra', 'VIC', '3141',
    1, 'Facebook/Instagram',
    'Mould appearing on bedroom window sills and surrounding walls in our apartment. It comes back within weeks of cleaning. Building management has not been responsive to complaints about ventilation.',
    'medium', 'residential_apartment',
    'new_lead', '2026-02-18 14:20:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'Tom Wilson', 'tom.wilson@yahoo.com.au', '0412300004',
    '7 Beach Road', 'Frankston', 'VIC', '3199',
    3, 'Google Ads',
    'Green mould on the subfloor timbers discovered during a bathroom renovation. The builder has stopped work and recommended getting a mould specialist to assess the extent of contamination before proceeding.',
    'emergency', 'residential_house',
    'new_lead', '2026-02-18 08:45:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'Maria Gonzalez', 'maria.gonzalez@hotmail.com', '0412300005',
    '33 Station Street', 'Box Hill', 'VIC', '3128',
    2, 'Customer Referral',
    'Persistent mould in the laundry room that keeps returning despite multiple attempts at cleaning with bleach. The room has poor ventilation and the dryer vents internally. Walls feel damp year-round.',
    'medium', 'residential_house',
    'new_lead', '2026-02-17 11:00:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'Ahmed Hassan', 'ahmed.hassan@gmail.com', '0412300006',
    'Suite 3/55 Collins Street', 'Melbourne', 'VIC', '3000',
    1, 'Phone Call (Direct)',
    'Mould discovered in the ceiling cavity of our commercial office space after a water leak from the floor above. Staff have been complaining about respiratory issues. Need urgent assessment for workplace safety compliance.',
    'emergency', 'commercial_office',
    'new_lead', '2026-02-17 15:30:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'Lisa Tran', 'lisa.tran@gmail.com', '0412300007',
    '88 High Street', 'Preston', 'VIC', '3072',
    2, 'Website Form',
    'Dark spots appearing on the ceiling of the living room and along the cornices. We think there might be a slow roof leak causing moisture buildup. The house was built in the 1970s and has not had recent roof work.',
    'medium', 'residential_house',
    'new_lead', '2026-02-16 09:50:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'Michael Brown', 'michael.brown@email.com', '0412300008',
    '5 The Esplanade', 'Brighton', 'VIC', '3186',
    2, 'Real Estate Agent',
    'Pre-purchase inspection revealed mould in the bathroom and subfloor areas. The property is a Victorian-era home. Need a detailed mould assessment report before proceeding with the settlement next month.',
    'high', 'residential_house',
    'new_lead', '2026-02-16 13:15:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'Yuki Tanaka', 'yuki.tanaka@outlook.com', '0412300009',
    'Apt 23/90 Dorcas Street', 'Southbank', 'VIC', '3006',
    1, 'Website Form',
    'Black mould growing around the bathroom exhaust fan and in the shower recess. The apartment has minimal natural ventilation and no window in the bathroom. Body corporate has been unresponsive about the building ventilation system.',
    'medium', 'residential_apartment',
    'new_lead', '2026-02-15 10:00:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'Daniel Kelly', 'daniel.kelly@icloud.com', '0412300010',
    '15 Main Street', 'Dandenong', 'VIC', '3175',
    3, 'Google Search (Organic)',
    'Mould along the bottom of external walls in the children''s bedroom. We have noticed it gets worse in winter months. Worried about the health impact on our kids who both have asthma.',
    'high', 'residential_house',
    'new_lead', '2026-02-15 16:40:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'Sofia Papadopoulos', 'sofia.papadopoulos@gmail.com', '0412300011',
    '42 Sydney Road', 'Brunswick', 'VIC', '3056',
    2, 'Website Form',
    'Significant mould growth found behind kitchen cabinets during a renovation. The plaster is soft and crumbling in patches. Need professional assessment to determine if it is surface mould or a deeper structural issue.',
    'high', 'residential_house',
    'new_lead', '2026-02-14 11:25:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'Ryan Cooper', 'ryan.cooper@protonmail.com', '0412300012',
    'Unit 5/18 Carlisle Street', 'St Kilda', 'VIC', '3182',
    1, 'Google Ads',
    'Mould patches on the bedroom ceiling that seem to be growing larger each week. The apartment above has had plumbing issues in the past. I am renting and need an official assessment report for my landlord.',
    'low', 'residential_apartment',
    'new_lead', '2026-02-14 08:30:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'Fatima Al-Rashidi', 'fatima.alrashidi@gmail.com', '0412300013',
    '67 Springvale Road', 'Glen Waverley', 'VIC', '3150',
    2, 'Customer Referral',
    'Our neighbour recommended your company after you helped them last year. We have mould in the ensuite bathroom and walk-in robe. The robe has a musty odour and some clothes have been damaged by mould spots.',
    'medium', 'residential_house',
    'new_lead', '2026-02-13 14:00:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'Jack Thompson', 'jack.thompson@gmail.com', '0412300014',
    '29 Warrigal Road', 'Caulfield', 'VIC', '3162',
    2, 'Website Form',
    'Mould on ceiling and walls of a ground-floor retail shop. It is affecting stock and the space smells damp. I suspect rising damp from the building foundations. Need assessment urgently before the health inspector visits next week.',
    'emergency', 'commercial_retail',
    'new_lead', '2026-02-13 09:20:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'Emma Davis', 'emma.davis@yahoo.com', '0412300015',
    '4 Barkers Road', 'Kew', 'VIC', '3101',
    2, 'Website Form',
    'Light grey mould spots appearing on the nursery room walls. We only moved in three months ago and are very concerned about our newborn. The previous owners may have painted over existing mould problems.',
    'high', 'residential_house',
    'new_lead', '2026-02-13 17:10:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  );

  -- =========================================================================
  -- GROUP 2: inspection_waiting (12 leads) — Assigned, inspection date set
  -- Created: Feb 5-12 2026, inspection dates: Feb 20 - Mar 5 2026
  -- =========================================================================
  INSERT INTO public.leads (
    full_name, email, phone,
    property_address_street, property_address_suburb, property_address_state, property_address_postcode,
    property_zone, lead_source, issue_description, urgency, property_type,
    status, assigned_to, inspection_scheduled_date, created_at
  ) VALUES
  (
    'Anthony Rossi', 'anthony.rossi@gmail.com', '0412300016',
    '23 Burke Road', 'Camberwell', 'VIC', '3124',
    2, 'Customer Referral',
    'Mould growing along the skirting boards in the living room and hallway. The carpet feels damp in the corners. We think there is a drainage issue on the south side of the house causing moisture to seep through.',
    'medium', 'residential_house',
    'inspection_waiting', tech_id, '2026-02-24',
    '2026-02-12 09:00:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'Mei Lin Wong', 'meilin.wong@outlook.com', '0412300017',
    'Unit 12/35 Errol Street', 'North Melbourne', 'VIC', '3051',
    1, 'Website Form',
    'Extensive black mould in the bathroom and kitchen of our apartment. The exhaust fans do not seem to work properly. My partner has developed a persistent cough since we moved in four months ago.',
    'high', 'residential_apartment',
    'inspection_waiting', tech_id, '2026-02-25',
    '2026-02-12 11:30:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'Patrick Murphy', 'patrick.murphy@email.com', '0412300018',
    '9 Cranbourne Road', 'Narre Warren', 'VIC', '3805',
    3, 'Google Search (Organic)',
    'Water stains and mould patches on the ceiling of the second bedroom. We had a roof leak repaired six months ago but the mould has continued to spread. The room smells musty even after airing out.',
    'medium', 'residential_house',
    'inspection_waiting', tech_id, '2026-02-25',
    '2026-02-11 14:45:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'Aisha Osman', 'aisha.osman@hotmail.com', '0412300019',
    '56 Barkly Street', 'Footscray', 'VIC', '3011',
    2, 'Property Manager',
    'Tenant has reported mould in the bedroom and bathroom of the rental property. Photos show significant growth on walls and ceiling. Need professional inspection and report for insurance and remediation planning.',
    'high', 'residential_apartment',
    'inspection_waiting', tech_id, '2026-02-26',
    '2026-02-10 10:15:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'Chris Taylor', 'chris.taylor@yahoo.com.au', '0412300020',
    '78 Nepean Highway', 'Moorabbin', 'VIC', '3189',
    2, 'Google Ads',
    'Mould found on the walls and ceiling of our warehouse storage area during annual stocktake. Some cardboard packaging has been affected. The building has poor ventilation and the roller doors let in moisture when open.',
    'low', 'commercial_industrial',
    'inspection_waiting', tech_id, '2026-02-27',
    '2026-02-10 08:30:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'Nina Petrova', 'nina.petrova@gmail.com', '0412300021',
    'Apt 4/88 Gertrude Street', 'Fitzroy', 'VIC', '3065',
    1, 'Website Form',
    'Mould in the bathroom of our heritage apartment. The tiles are original and we cannot modify the ventilation without body corporate approval. Looking for a professional assessment and recommendation for the body corporate meeting.',
    'medium', 'residential_apartment',
    'inspection_waiting', tech_id, '2026-02-27',
    '2026-02-09 15:20:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'Ben Stewart', 'ben.stewart@icloud.com', '0412300022',
    '14 Sladen Street', 'Cranbourne', 'VIC', '3977',
    3, 'Customer Referral',
    'Mould on the external brick walls of the garage and in the attached laundry. The downpipes seem to be overflowing during rain and water pools near the foundation. Need inspection to assess structural risk.',
    'high', 'residential_house',
    'inspection_waiting', tech_id, '2026-02-28',
    '2026-02-08 09:45:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'Rachel Kim', 'rachel.kim@gmail.com', '0412300023',
    '31 Whitehorse Road', 'Balwyn', 'VIC', '3103',
    2, 'Google Search (Organic)',
    'Mould spots appearing on the ceiling of the master bedroom after recent heavy rainfall. The roof was inspected last year and no leaks were found. Suspecting condensation issue due to poor ceiling insulation.',
    'medium', 'residential_house',
    'inspection_waiting', tech_id, '2026-03-02',
    '2026-02-07 13:00:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'Luke Henderson', 'luke.henderson@email.com', '0412300024',
    '6 Dalton Road', 'Epping', 'VIC', '3076',
    3, 'Phone Call (Direct)',
    'Extensive mould discovered in the manufacturing floor of our factory after a roof leak during last week''s storms. Workers have been relocated to another section. WorkSafe notified and we need urgent assessment and clearance certificate.',
    'emergency', 'commercial_industrial',
    'inspection_waiting', tech_id, '2026-02-24',
    '2026-02-07 07:30:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'Zara Patel', 'zara.patel@outlook.com', '0412300025',
    'Unit 2/44 Chapel Street', 'Prahran', 'VIC', '3181',
    1, 'Facebook/Instagram',
    'Mould in common areas of our three-storey strata building including stairwell walls and basement car park ceiling. Multiple residents have complained. Body corporate has approved a professional inspection.',
    'medium', 'strata',
    'inspection_waiting', tech_id, '2026-03-03',
    '2026-02-06 11:15:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'Mark Robinson', 'mark.robinson@gmail.com', '0412300026',
    '19 High Street', 'Berwick', 'VIC', '3806',
    3, 'Website Form',
    'Small amount of mould noticed in the corner of the spare bedroom ceiling. House is relatively new, built five years ago. Want to get it checked before it becomes a bigger problem.',
    'low', 'residential_house',
    'inspection_waiting', tech_id, '2026-03-04',
    '2026-02-05 16:00:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'Olivia Wang', 'olivia.wang@hotmail.com', '0412300027',
    '52 Glenferrie Road', 'Malvern', 'VIC', '3144',
    2, 'Real Estate Agent',
    'Vendor disclosure mentioned previous mould remediation in the subfloor. As the buyer''s agent I need an independent mould assessment before settlement. The property is a 1920s California bungalow.',
    'high', 'residential_house',
    'inspection_waiting', tech_id, '2026-03-05',
    '2026-02-05 10:30:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  );

  -- =========================================================================
  -- GROUP 3: inspection_ai_summary (6 leads) — Inspection done, AI reviewing
  -- Created: Jan 30 - Feb 5 2026
  -- =========================================================================
  INSERT INTO public.leads (
    full_name, email, phone,
    property_address_street, property_address_suburb, property_address_state, property_address_postcode,
    property_zone, lead_source, issue_description, urgency, property_type,
    status, assigned_to, inspection_scheduled_date, inspection_completed_date, created_at
  ) VALUES
  (
    'Sam Fitzgerald', 'sam.fitzgerald@gmail.com', '0412300028',
    '77 Bay Street', 'Port Melbourne', 'VIC', '3207',
    1, 'Website Form',
    'Mould in the bathroom and laundry of a ground-floor apartment near the waterfront. High humidity area. The building is ten years old and multiple units are affected according to neighbours.',
    'high', 'residential_apartment',
    'inspection_ai_summary', tech_id, '2026-02-10', '2026-02-10',
    '2026-02-04 09:30:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'Helen Nguyen', 'helen.nguyen@email.com', '0412300029',
    '3 Railway Parade', 'Carnegie', 'VIC', '3163',
    2, 'Customer Referral',
    'Mould on the bathroom ceiling tiles and around the window frame in the kitchen. The house has been vacant for two months during renovation. Ventilation was blocked by temporary construction sheeting.',
    'medium', 'residential_house',
    'inspection_ai_summary', tech_id, '2026-02-08', '2026-02-08',
    '2026-02-03 14:00:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'George Dimitriou', 'george.dimitriou@outlook.com', '0412300030',
    '48 Separation Street', 'Northcote', 'VIC', '3070',
    2, 'Google Search (Organic)',
    'Dark mould patches on the bedroom walls and wardrobe interior. The room is on the south side of the house and gets very little sunlight. Dehumidifier has been running but mould keeps returning.',
    'medium', 'residential_house',
    'inspection_ai_summary', tech_id, '2026-02-07', '2026-02-07',
    '2026-02-02 10:45:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'Amy Turner', 'amy.turner@yahoo.com', '0412300031',
    '16 Davey Street', 'Frankston', 'VIC', '3199',
    3, 'Google Ads',
    'Mould affecting multiple units in our strata complex. Common hallways, underground parking, and individual bathrooms all showing growth. Strata manager has engaged us for a full building assessment.',
    'emergency', 'strata',
    'inspection_ai_summary', tech_id, '2026-02-06', '2026-02-06',
    '2026-01-31 08:15:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'Raj Kapoor', 'raj.kapoor@gmail.com', '0412300032',
    '25 Centre Road', 'Bentleigh', 'VIC', '3204',
    2, 'Property Manager',
    'Mould found in the underground car park ceiling and stairwell walls of a six-unit residential complex. Water appears to be seeping through from ground level. Body corporate has approved inspection for remediation quote.',
    'low', 'strata',
    'inspection_ai_summary', tech_id, '2026-02-05', '2026-02-05',
    '2026-01-30 15:30:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'Jessica Hall', 'jessica.hall@icloud.com', '0412300033',
    '8 Thompson Avenue', 'Werribee', 'VIC', '3030',
    3, 'Facebook/Instagram',
    'Mould in the ensuite and main bathroom after recent flooding in the area. The carpets were water-damaged and replaced but the walls were not properly dried. Musty smell persists throughout the house.',
    'high', 'residential_house',
    'inspection_ai_summary', tech_id, '2026-02-04', '2026-02-04',
    '2026-01-30 09:00:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  );

  -- =========================================================================
  -- GROUP 4: approve_inspection_report (5 leads) — Report ready for approval
  -- Created: Jan 27 - Feb 2 2026
  -- =========================================================================
  INSERT INTO public.leads (
    full_name, email, phone,
    property_address_street, property_address_suburb, property_address_state, property_address_postcode,
    property_zone, lead_source, issue_description, urgency, property_type,
    status, assigned_to, inspection_scheduled_date, inspection_completed_date, created_at
  ) VALUES
  (
    'Nathan Wright', 'nathan.wright@gmail.com', '0412300034',
    '11 Albert Street', 'Coburg', 'VIC', '3058',
    2, 'Google Search (Organic)',
    'Mould throughout the bathroom, laundry and kitchen of our 1960s weatherboard home. We have tried commercial mould removal products but it returns within a few weeks. Need professional remediation quote.',
    'high', 'residential_house',
    'approve_inspection_report', tech_id, '2026-02-01', '2026-02-01',
    '2026-02-01 10:00:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'Tanya Kowalski', 'tanya.kowalski@email.com', '0412300035',
    'Unit 6/30 Glen Eira Road', 'Elsternwick', 'VIC', '3185',
    2, 'Customer Referral',
    'Mould on the ceiling and around the window frames of our second-floor apartment. Building is 30 years old. The owner has asked for a professional report before approving remediation work.',
    'medium', 'residential_apartment',
    'approve_inspection_report', tech_id, '2026-01-30', '2026-01-30',
    '2026-01-29 13:45:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'Steve Martin', 'steve.martin@outlook.com', '0412300036',
    '63 Lygon Street', 'Carlton', 'VIC', '3053',
    1, 'Phone Call (Direct)',
    'Mould discovered in the ceiling tiles and air conditioning ducts of our office space during routine HVAC maintenance. The office is leased and we need a report for the landlord to action repairs.',
    'low', 'commercial_office',
    'approve_inspection_report', tech_id, '2026-01-29', '2026-01-29',
    '2026-01-28 09:30:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'Claire O''Sullivan', 'claire.osullivan@gmail.com', '0412300037',
    '21 Evans Street', 'Sunbury', 'VIC', '3429',
    3, 'Facebook/Instagram',
    'Mould in the walk-in robe and ensuite of our five-year-old home. We believe it is related to poor waterproofing in the ensuite shower. Builder warranty has expired. Need assessment and remediation options.',
    'medium', 'residential_house',
    'approve_inspection_report', tech_id, '2026-01-28', '2026-01-28',
    '2026-01-27 14:15:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'David Lee', 'david.lee@hotmail.com', '0412300038',
    '40 Main Road', 'Pakenham', 'VIC', '3810',
    3, 'Website Form',
    'Mould under the house in the subfloor area and rising damp in the living room walls. The house is on stumps and the subfloor ventilation seems blocked. Moisture readings are very high according to our builder.',
    'high', 'residential_house',
    'approve_inspection_report', tech_id, '2026-01-28', '2026-01-28',
    '2026-01-27 08:00:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  );

  -- =========================================================================
  -- GROUP 5: inspection_email_approval (4 leads) — Approved, pending email
  -- Created: Jan 25-30 2026
  -- =========================================================================
  INSERT INTO public.leads (
    full_name, email, phone,
    property_address_street, property_address_suburb, property_address_state, property_address_postcode,
    property_zone, lead_source, issue_description, urgency, property_type,
    status, assigned_to, inspection_scheduled_date, inspection_completed_date, created_at
  ) VALUES
  (
    'Rebecca Morris', 'rebecca.morris@gmail.com', '0412300039',
    '17 Station Street', 'Thornbury', 'VIC', '3071',
    2, 'Google Search (Organic)',
    'Mould affecting three units in our eight-unit strata building. The plumbing stack appears to be leaking behind bathroom walls on multiple floors. Body corporate needs a professional report for the insurance claim.',
    'medium', 'strata',
    'inspection_email_approval', tech_id, '2026-01-27', '2026-01-27',
    '2026-01-29 11:00:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'Alex Volkov', 'alex.volkov@outlook.com', '0412300040',
    '5/22 Harbour Esplanade', 'Docklands', 'VIC', '3008',
    1, 'Property Manager',
    'Mould on the interior walls and ceiling of a commercial office suite in a waterfront building. High humidity levels recorded. The tenants have raised OHS concerns and we need a formal assessment report.',
    'low', 'commercial_office',
    'inspection_email_approval', tech_id, '2026-01-26', '2026-01-26',
    '2026-01-28 09:45:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'Megan Campbell', 'megan.campbell@yahoo.com.au', '0412300041',
    '35 Coburns Road', 'Melton', 'VIC', '3337',
    3, 'Customer Referral',
    'Mould on bathroom walls and in the linen cupboard that backs onto the bathroom. The exhaust fan is noisy and may not be extracting properly. Have a toddler and want it resolved before winter.',
    'medium', 'strata',
    'inspection_email_approval', tech_id, '2026-01-25', '2026-01-25',
    '2026-01-26 14:30:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'Peter Zhang', 'peter.zhang@email.com', '0412300042',
    '73 Mason Street', 'Newport', 'VIC', '3015',
    2, 'Real Estate Agent',
    'Mould in the subfloor and lower walls of a property being prepared for sale. The agent wants a clearance certificate after remediation. Previous owner did not maintain subfloor ventilation.',
    'high', 'residential_apartment',
    'inspection_email_approval', tech_id, '2026-01-25', '2026-01-25',
    '2026-01-25 10:15:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  );

  -- =========================================================================
  -- GROUP 6: closed (5 leads) — Successfully completed
  -- Created: Jan 20-25 2026
  -- =========================================================================
  INSERT INTO public.leads (
    full_name, email, phone,
    property_address_street, property_address_suburb, property_address_state, property_address_postcode,
    property_zone, lead_source, issue_description, urgency, property_type,
    status, assigned_to,
    inspection_scheduled_date, inspection_completed_date,
    job_scheduled_date, job_completed_date,
    notes, created_at
  ) VALUES
  (
    'Jenny Anderson', 'jenny.anderson@gmail.com', '0412300043',
    '28 Pakington Street', 'Geelong', 'VIC', '3220',
    4, 'Website Form',
    'Mould in the bathroom and two bedrooms of our weatherboard cottage. The subfloor was damp and had inadequate ventilation. Professional remediation was completed including new subfloor fans installed.',
    'high', 'residential_house',
    'closed', tech_id,
    '2026-01-22', '2026-01-22',
    '2026-01-27', '2026-01-28',
    'Job completed successfully. Subfloor fans installed, all mould treated. Customer very satisfied with result.',
    '2026-01-20 09:00:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'Robert Singh', 'robert.singh@outlook.com', '0412300044',
    '9 Buckley Street', 'Essendon', 'VIC', '3040',
    2, 'Google Search (Organic)',
    'Mould in the en-suite bathroom and adjacent bedroom closet. Shower waterproofing had failed causing moisture to penetrate the wall cavity. Full remediation and waterproofing repair completed.',
    'medium', 'residential_apartment',
    'closed', tech_id,
    '2026-01-23', '2026-01-23',
    '2026-01-29', '2026-01-30',
    'Waterproofing repair done by plumber, mould remediation completed same day. Follow-up inspection clear.',
    '2026-01-21 10:30:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'Laura McPherson', 'laura.mcpherson@icloud.com', '0412300045',
    'Unit 3/15 Main Street', 'Mornington', 'VIC', '3931',
    4, 'Facebook/Instagram',
    'Mould in the kitchen and bathroom of a holiday rental apartment near the beach. High humidity and infrequent use contributed to the growth. Remediation completed and dehumidifier installed.',
    'low', 'residential_apartment',
    'closed', tech_id,
    '2026-01-24', '2026-01-24',
    '2026-01-30', '2026-01-31',
    'Holiday rental property. Dehumidifier installed for ongoing moisture control. Owner educated on ventilation best practices.',
    '2026-01-22 13:00:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'Kevin Tran', 'kevin.tran@yahoo.com', '0412300046',
    '54 Sturt Street', 'Ballarat', 'VIC', '3350',
    4, 'Google Ads',
    'Mould on the walls and ceiling of a retail shop in a heritage building. The building has poor drainage and the shop is below street level. Full remediation and sealing treatment completed.',
    'low', 'commercial_retail',
    'closed', tech_id,
    '2026-01-25', '2026-01-25',
    '2026-02-01', '2026-02-03',
    'Heritage building required careful treatment. Anti-mould coating applied. Drainage improvement recommended to building owner.',
    '2026-01-23 08:45:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'Hannah Blake', 'hannah.blake@gmail.com', '0412300047',
    '81 Queen Street', 'Warragul', 'VIC', '3820',
    4, 'Real Estate Agent',
    'Pre-sale mould inspection and remediation of a rural property. Mould found in subfloor and bathroom areas. Full treatment completed and clearance certificate provided for the property listing.',
    'low', 'residential_house',
    'closed', tech_id,
    '2026-01-24', '2026-01-24',
    '2026-01-31', '2026-02-01',
    'Pre-sale clearance certificate issued. Property now listed. Agent confirmed report was satisfactory for buyers.',
    '2026-01-22 15:30:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  );

  -- =========================================================================
  -- GROUP 7: not_landed (3 leads) — Lost/rejected
  -- Created: Jan 20-30 2026
  -- =========================================================================
  INSERT INTO public.leads (
    full_name, email, phone,
    property_address_street, property_address_suburb, property_address_state, property_address_postcode,
    property_zone, lead_source, issue_description, urgency, property_type,
    status, assigned_to, notes, internal_notes, created_at
  ) VALUES
  (
    'Tony Caruso', 'tony.caruso@email.com', '0412300048',
    '38 Simpson Street', 'East Melbourne', 'VIC', '3002',
    1, 'Website Form',
    'Mould in the office kitchenette and server room of our commercial space. The air conditioning system may be contributing to moisture buildup. Wanted a quote for assessment and remediation.',
    'medium', 'commercial_office',
    'not_landed', tech_id,
    'Customer decided to go with a cheaper competitor. Follow up in 3 months if issue persists.',
    'Quoted $2,200 for full assessment. Customer said another company offered $1,400. Lost on price.',
    '2026-01-28 10:00:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'Stephanie Price', 'stephanie.price@hotmail.com', '0412300049',
    '14 Foster Street', 'Dandenong', 'VIC', '3175',
    3, 'Website Form',
    'Mould spots on the bedroom walls and ceiling. Renting the property and landlord is not responsive to maintenance requests. Wanted an inspection report to present to the landlord.',
    'low', 'residential_house',
    'not_landed', tech_id,
    'Tenant could not get landlord approval for the inspection. Advised to contact Consumer Affairs Victoria.',
    'Tenant inquiry - landlord refused to pay for inspection. Tenant cannot afford to self-fund.',
    '2026-01-25 14:00:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  ),
  (
    'Will Edwards', 'will.edwards@gmail.com', '0412300050',
    '27 Bay Road', 'Sandringham', 'VIC', '3191',
    2, 'Website Form',
    'Minor mould on the garage ceiling and some spots in the laundry. Wanted a quote but decided the issue was small enough to handle with DIY products from the hardware store.',
    'medium', 'commercial_industrial',
    'not_landed', tech_id,
    'Customer decided to DIY after learning the scope. Advised to call back if issue worsens or returns.',
    'Small job, customer felt our minimum call-out fee was too high for the scope. Understandable.',
    '2026-01-23 11:30:00'::timestamp AT TIME ZONE 'Australia/Melbourne'
  );

  RAISE NOTICE 'Successfully seeded 50 realistic Melbourne leads.';
  RAISE NOTICE 'Status breakdown: 15 new_lead, 12 inspection_waiting, 6 inspection_ai_summary, 5 approve_inspection_report, 4 inspection_email_approval, 5 closed, 3 not_landed';
END $$;

-- =============================================================================
-- VERIFICATION QUERIES (run after seeding)
-- =============================================================================

-- Count by status
SELECT status, count(*) as cnt
FROM public.leads
GROUP BY status
ORDER BY cnt DESC;

-- Verify lead_numbers were auto-generated
SELECT lead_number, full_name, status, created_at AT TIME ZONE 'Australia/Melbourne' as melbourne_time
FROM public.leads
ORDER BY created_at DESC
LIMIT 15;

-- Verify zone distribution
SELECT property_zone, count(*) as cnt
FROM public.leads
GROUP BY property_zone
ORDER BY property_zone;

-- Verify urgency distribution
SELECT urgency, count(*) as cnt
FROM public.leads
GROUP BY urgency
ORDER BY cnt DESC;

-- Verify lead source distribution
SELECT lead_source, count(*) as cnt
FROM public.leads
GROUP BY lead_source
ORDER BY cnt DESC;
