// Inspection-report HTML hashing for the PDF pipeline mismatch guard.
//
// The HTML returned by `generate-inspection-pdf` is byte-identical for the
// same underlying inspection data EXCEPT for one source of volatility:
// photo URLs include signed-URL query strings (token + expiration) that are
// freshly generated by `supabase.storage.createSignedUrl()` on every EF call.
// We strip those query strings before hashing so the hash describes the
// content, not the access tokens. See docs/PDF_PIPELINE_PLAN.md Phase 0 for
// the determinism audit that justifies this rule.

// Matches Supabase storage URLs (public or signed) and captures the bucket
// path WITHOUT the query string. Replacement keeps the URL up to the path
// segment, drops the `?token=...&expires=...&...` tail.
const SUPABASE_STORAGE_URL_RE =
  /(https?:\/\/[^/\s"']+\/storage\/v1\/object\/(?:sign|public)\/[^?"'\s]+)\?[^"'\s]*/g;

export function normalizeHtmlForHash(html: string): string {
  return html.replace(SUPABASE_STORAGE_URL_RE, '$1');
}

export async function hashHtml(html: string): Promise<string> {
  const normalized = normalizeHtmlForHash(html);
  const bytes = new TextEncoder().encode(normalized);
  const digest = await crypto.subtle.digest('SHA-256', bytes);
  return Array.from(new Uint8Array(digest))
    .map((b) => b.toString(16).padStart(2, '0'))
    .join('');
}
