-- Migration: Drop backup/snapshot tables (pre-launch cleanup)
-- Created: 2026-07-07
-- Author: database-specialist agent
--
-- Purpose:
-- Drops all 15 backup/snapshot tables in the public schema identified by the
-- pre-launch audit in docs/BACKUP_TABLE_CLEANUP.md (2026-07-07). Every table is:
--   * RLS-DISABLED with 0 policies (unprotected backups of PII-bearing
--     leads / inspections / photos data),
--   * referenced by NO live application code (no src/ query, no edge function;
--     only stale type declarations in src/integrations/supabase/types.ts and the
--     original CREATE migrations),
--   * past all retention windows (the dead-col-drop backups were created
--     2026-05-13 with a 30-day retention note — now >50 days elapsed).
-- Total rows removed across all 15 tables: 158.
--
-- Rationale for cleanup: shrink the unprotected-PII attack surface and reduce
-- schema clutter ahead of the 2026-07-13 hybrid cutover.
--
-- REVERSIBILITY (per DB migration rules):
-- DROP TABLE is destructive — the row data cannot be regenerated by a down
-- migration. The ONLY rollback path is restoring from the fresh dump/backup taken
-- BEFORE running this migration (Post-Drop Checklist in docs/BACKUP_TABLE_CLEANUP.md).
-- Do not run this migration until that backup exists and is verified.
--
-- APPLICATION: human-applied via the Supabase Studio SQL editor. Recommended order:
-- run against DEV (ctppzqnysmzynkxjlzta) first, verify, then PROD (ecyivrxjpsmjmexqatym).
-- After a successful run, regenerate TypeScript types to remove the 15 dead
-- declarations:
--   npx supabase gen types typescript --project-id ecyivrxjpsmjmexqatym \
--     > src/integrations/supabase/types.ts
--
-- No CASCADE is used: these tables have no known dependents, and an unexpected
-- dependency should error loudly rather than silently cascade.

BEGIN;

-- Group 1: dead-col-drop backups (Phase 5, 2026-05-13) — 29 rows
DROP TABLE IF EXISTS public.leads_dead_col_drop_backup_20260513;
DROP TABLE IF EXISTS public.inspections_dead_col_drop_backup_20260513;
DROP TABLE IF EXISTS public.inspection_areas_dead_col_drop_backup_20260513;
DROP TABLE IF EXISTS public.subfloor_data_dead_col_drop_backup_20260513;
DROP TABLE IF EXISTS public.moisture_readings_dead_col_drop_backup_20260513;

-- Group 2: revert-cleanup backups (2026-04-29) — 4 rows
DROP TABLE IF EXISTS public.calendar_bookings_revert_cleanup_backup_20260429;
DROP TABLE IF EXISTS public.leads_revert_cleanup_backup_20260429;

-- Group 3: dew-point backfill backups (wave_6_1_pr4, 2026-05-14) — 7 rows
DROP TABLE IF EXISTS public.inspection_areas_dew_point_backfill_backup;
DROP TABLE IF EXISTS public.inspections_outdoor_dew_point_backup;

-- Group 4: backfill snapshots (discount 2026-05-13, lead source 2026-05-14) — 21 rows
DROP TABLE IF EXISTS public.inspections_discount_backfill_backup_20260513;
DROP TABLE IF EXISTS public.leads_source_backfill_backup_20260514;

-- Group 5: restore backup (wave_6_1_pr4, 2026-05-14) — 3 rows
DROP TABLE IF EXISTS public.inspections_subfloor_required_restore_backup;

-- Group 6: plain point-in-time backups (Studio-created) — 94 rows
DROP TABLE IF EXISTS public.leads_backup_20260428;
DROP TABLE IF EXISTS public.photos_backup_20260526;
DROP TABLE IF EXISTS public.photos_subfloor_snapshot_20260527;

COMMIT;

-- Post-drop verification (run separately after COMMIT — expect 0 rows):
-- SELECT table_name
-- FROM information_schema.tables
-- WHERE table_schema = 'public'
--   AND table_name IN (
--     'calendar_bookings_revert_cleanup_backup_20260429',
--     'inspection_areas_dead_col_drop_backup_20260513',
--     'inspection_areas_dew_point_backfill_backup',
--     'inspections_dead_col_drop_backup_20260513',
--     'inspections_discount_backfill_backup_20260513',
--     'inspections_outdoor_dew_point_backup',
--     'inspections_subfloor_required_restore_backup',
--     'leads_backup_20260428',
--     'leads_dead_col_drop_backup_20260513',
--     'leads_revert_cleanup_backup_20260429',
--     'leads_source_backfill_backup_20260514',
--     'moisture_readings_dead_col_drop_backup_20260513',
--     'photos_backup_20260526',
--     'photos_subfloor_snapshot_20260527',
--     'subfloor_data_dead_col_drop_backup_20260513'
--   );
