// This file is automatically generated. Do not edit it directly.
import { createClient, SupportedStorage } from '@supabase/supabase-js';
import type { Database } from '@/types/database.types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_ANON_KEY;

// Validate environment variables at runtime
if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  throw new Error(
    'Missing Supabase environment variables. Please ensure VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY are set in .env.local'
  );
}

// Key used to track "Remember Me" preference
const REMEMBER_ME_KEY = 'mrc_remember_me_preference';

// Key used by Supabase to store auth tokens
const SUPABASE_AUTH_TOKEN_KEY = `sb-${new URL(SUPABASE_URL).hostname.split('.')[0]}-auth-token`;

/**
 * Custom storage adapter that switches between localStorage and sessionStorage
 * based on the "Remember Me" preference.
 *
 * - Remember Me CHECKED: Uses localStorage (persists across browser sessions)
 * - Remember Me UNCHECKED: Uses sessionStorage (cleared when browser closes)
 */
class RememberMeStorage implements SupportedStorage {
  private getStorage(): Storage {
    // Check the remember me preference from localStorage (always stored there)
    const rememberMe = localStorage.getItem(REMEMBER_ME_KEY) === 'true';
    return rememberMe ? localStorage : sessionStorage;
  }

  getItem(key: string): string | null {
    // For the auth token, check both storages and return whichever has it
    // This handles the case when preference changes between sessions
    if (key === SUPABASE_AUTH_TOKEN_KEY) {
      const fromLocal = localStorage.getItem(key);
      const fromSession = sessionStorage.getItem(key);
      return fromLocal || fromSession;
    }
    return this.getStorage().getItem(key);
  }

  setItem(key: string, value: string): void {
    const storage = this.getStorage();

    // If this is the auth token, make sure to clear from the other storage
    // to prevent duplicate sessions
    if (key === SUPABASE_AUTH_TOKEN_KEY) {
      const otherStorage = storage === localStorage ? sessionStorage : localStorage;
      otherStorage.removeItem(key);
    }

    storage.setItem(key, value);
  }

  removeItem(key: string): void {
    // Remove from both storages to ensure clean logout
    localStorage.removeItem(key);
    sessionStorage.removeItem(key);
  }
}

// Create the custom storage instance
const rememberMeStorage = new RememberMeStorage();

/**
 * Set the "Remember Me" preference before signing in.
 * This determines whether the session persists after browser close.
 *
 * @param value - true for persistent session (30 days), false for session-only
 */
export function setRememberMePreference(value: boolean): void {
  localStorage.setItem(REMEMBER_ME_KEY, String(value));

  if (import.meta.env.DEV) {
    console.log(`🔐 [Remember Me] Set to: ${value ? 'persistent (localStorage)' : 'session-only (sessionStorage)'}`);
  }
}

/**
 * Get the current "Remember Me" preference.
 */
export function getRememberMePreference(): boolean {
  return localStorage.getItem(REMEMBER_ME_KEY) === 'true';
}

/**
 * Clear auth tokens from both storages (used during sign out).
 */
export function clearAuthTokens(): void {
  localStorage.removeItem(SUPABASE_AUTH_TOKEN_KEY);
  sessionStorage.removeItem(SUPABASE_AUTH_TOKEN_KEY);
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    // CRITICAL: Enable session persistence across page reloads
    persistSession: true,

    // CRITICAL: Use custom storage that switches based on Remember Me preference
    storage: rememberMeStorage,

    // CRITICAL: Auto-refresh tokens before they expire
    autoRefreshToken: true,

    // CRITICAL: Detect session from URL (for password reset links)
    detectSessionInUrl: true,

    // CRITICAL: Use implicit flow for password recovery
    // PKCE converts ?token_hash= to ?code= which creates regular session, not recovery session
    // Password updates require recovery session (403 error with regular session)
    flowType: 'implicit',

    // Debug mode (only in development)
    debug: import.meta.env.DEV,
  },

  // Global options
  global: {
    headers: {
      'x-application-name': 'mrc-lead-management',
    },
  },
});

// Log session state changes in development (helpful for debugging password reset issues)
if (import.meta.env.DEV) {
  supabase.auth.onAuthStateChange((event, session) => {
    console.log('🔐 [Supabase Client] Auth State Change:', event);
    console.log('📝 [Supabase Client] Session:', session ? 'Active' : 'None');
    if (session) {
      console.log('👤 [Supabase Client] User:', session.user.email);
      console.log('⏰ [Supabase Client] Expires:', new Date(session.expires_at! * 1000).toLocaleString());
      console.log('💾 [Supabase Client] Storage:', getRememberMePreference() ? 'localStorage (persistent)' : 'sessionStorage (session-only)');
    }
  });
}
